/**
 * AI bug-report generator.
 *
 * Every other tool gives you a stack trace and the literal failed assertion.
 * Luna gives you a 1-paragraph human-readable bug report:
 *
 *   "Expected the cart total to be $19.99 after adding the t-shirt, but the
 *    cart showed $0.00. Likely cause: the 'Add to cart' button click didn't
 *    register — possibly because the button is disabled until size is
 *    selected. Suggested fix: select a size before adding to cart."
 *
 * Designed to drop straight into a GitHub Issue / Jira / Linear ticket.
 *
 * Called automatically by the run-completion path in the server when a run
 * fails. Posted as the `bug_report` field of the outbound webhook payload.
 */
import { chat, type ChatMsg } from "./llm.js";
import type { RunReport } from "./report.js";
import type { Plan } from "./plan.js";

export interface BugReport {
  /** One-paragraph human-readable summary suitable for a ticket title + body. */
  summary: string;
  /** Suggested first-pass fix the engineer should investigate. */
  suggested_fix: string;
  /** What the user should expect to see if the fix works. */
  expected_after_fix: string;
}

const SYSTEM = `You are a senior QA engineer writing a bug report from a failed AI-driven test run.

You will receive:
  - the test PLAN (name + intents + assertions)
  - the RUN result (which intents failed, which assertions failed, error messages, action history)

Output ONE JSON object with three string fields:

  {
    "summary": "Concise 2-3 sentence summary of what was being tested and what actually happened. Names the broken behaviour in concrete terms (no 'the test failed').",
    "suggested_fix": "One actionable suggestion for the engineer. If you can't tell, say 'Investigate <specific-element>' rather than guess.",
    "expected_after_fix": "One sentence describing what the user should see when the bug is fixed."
  }

RULES:
  - Be CONCRETE. Quote actual button text / element labels / values when you have them.
  - Don't blame the test framework — assume the app under test is wrong.
  - If the failure is clearly an environmental issue (page didn't load, 5xx error), say so explicitly.
  - No preamble, no commentary, no code fences. Output the JSON object only.`;

export async function generateBugReport(plan: Plan, report: RunReport): Promise<BugReport | null> {
  if (report.passed) return null;

  // Cap how much we send to the LLM — long action histories blow context.
  const failedIntents = report.intents
    .filter((it) => it.outcome !== "satisfied")
    .slice(0, 5)
    .map((it, i) => `Intent ${i + 1}: ${it.intent}\n  outcome: ${it.outcome}\n  reason: ${(it.finalReason ?? "(none)").slice(0, 200)}\n  steps: ${it.steps.length}`);

  const failedAssertions = report.assertions
    .filter((a) => !a.pass)
    .slice(0, 5)
    .map((a, i) => `Assertion ${i + 1}: ${a.assertion}\n  reason: ${a.reason.slice(0, 200)}`);

  const messages: ChatMsg[] = [
    { role: "system", content: SYSTEM },
    { role: "user", content:
      `PLAN: ${plan.name}\n` +
      `TARGET: ${plan.target}\n\n` +
      `INTENTS (planned):\n${plan.intents.map((it, i) => `  ${i + 1}. ${it}`).join("\n")}\n\n` +
      `ASSERTIONS (planned):\n${plan.assertions.map((a, i) => `  ${i + 1}. ${a}`).join("\n")}\n\n` +
      `WHAT FAILED:\n` +
      (failedIntents.length ? failedIntents.join("\n\n") + "\n\n" : "") +
      (failedAssertions.length ? failedAssertions.join("\n\n") : "(no assertion failures)") +
      `\n\nProduce the JSON bug report now.`,
    },
  ];

  try {
    const raw = await chat(messages, { maxTokens: 600, timeoutMs: 30_000 });
    const m = raw.match(/\{[\s\S]*\}/);
    if (!m) return null;
    const obj = JSON.parse(m[0]) as Partial<BugReport>;
    if (!obj.summary) return null;
    return {
      summary: obj.summary,
      suggested_fix: obj.suggested_fix ?? "(LLM did not provide a fix suggestion)",
      expected_after_fix: obj.expected_after_fix ?? "(LLM did not provide an expectation)",
    };
  } catch {
    return null;
  }
}

/** GitHub-Issue-flavoured rendering of the bug report — Markdown body. */
export function renderBugReportMarkdown(plan: Plan, report: RunReport, br: BugReport): string {
  return [
    `## ${br.summary.split(".")[0] ?? "Test failure"}`,
    "",
    br.summary,
    "",
    `**Suggested fix:** ${br.suggested_fix}`,
    "",
    `**Expected after fix:** ${br.expected_after_fix}`,
    "",
    "---",
    "",
    `**Plan:** \`${plan.name}\``,
    `**Target:** ${plan.target}`,
    `**Run duration:** ${(report.durationMs / 1000).toFixed(1)}s`,
    `**Failed intents:** ${report.intents.filter((it) => it.outcome !== "satisfied").length}/${report.intents.length}`,
    `**Failed assertions:** ${report.assertions.filter((a) => !a.pass).length}/${report.assertions.length}`,
    "",
    "_Generated by Luna Orbit · `bug_report` event._",
  ].join("\n");
}
